// GEO articles — bilingual content used by the /articles list and detail pages.
// Each article renders block-by-block; a { t: "cta" } block injects the inline
// purchase CTA. A bottom CTA is always appended by the detail page.

export type ArticleBlock =
  | { t: "h2"; x: string }
  | { t: "p"; x: string } // may contain simple <b> markup
  | { t: "ul"; items: string[] }
  | { t: "ol"; items: string[] }
  | { t: "quote"; x: string }
  | { t: "cta" };

export interface ArticleContent {
  title: string;
  description: string;
  category: string;
  readMins: number;
  blocks: ArticleBlock[];
}

export interface Article {
  slug: string;
  date: string; // ISO (publish date)
  ko: ArticleContent;
  en: ArticleContent;
}

export const articles: Article[] = [
  {
    slug: "what-is-geo",
    date: "2026-08-01",
    ko: {
      title: "GEO란 무엇인가: AI 시대의 새로운 검색 최적화",
      description:
        "GEO(생성형 엔진 최적화)의 정의와 SEO와의 차이, 그리고 AI가 답변에 당신의 페이지를 인용하게 만드는 것이 왜 비즈니스 생존과 직결되는지 설명합니다.",
      category: "기초",
      readMins: 6,
      blocks: [
        { t: "p", x: "사람들이 정보를 찾는 방식이 근본적으로 바뀌고 있습니다. 검색창에 키워드를 넣고 링크 10개를 훑던 시대에서, ChatGPT·Perplexity·Gemini에게 질문하고 <b>합성된 답변 하나</b>를 받는 시대로 넘어가고 있죠. 이 변화는 웹사이트를 운영하는 모든 사람에게 새로운 과제를 던집니다." },
        { t: "h2", x: "GEO의 정의" },
        { t: "p", x: "<b>GEO(Generative Engine Optimization, 생성형 엔진 최적화)</b>는 생성형 AI가 답변을 만들 때 당신의 페이지를 <b>신뢰할 만한 출처로 인용</b>하도록 콘텐츠와 기술 요소를 최적화하는 작업입니다. AI 답변에 인용되면 그 자체가 강력한 추천이 되고, 사용자는 인용된 출처를 클릭해 당신의 사이트로 유입됩니다." },
        { t: "h2", x: "SEO와 무엇이 다른가" },
        { t: "p", x: "SEO는 검색 결과 페이지에서 <b>순위</b>를 다투는 게임입니다. 상위 10위 안에 드는 것이 목표죠. 반면 GEO는 AI가 만드는 답변의 <b>좁은 인용 자리</b>에 드는 게임입니다. 그 답변은 보통 두세 개에서 일고여덟 개의 도메인만 출처로 언급합니다." },
        { t: "ul", items: [
          "SEO: 키워드, 백링크, 검색 순위 중심",
          "GEO: 사실 밀도, 인용 가능성, 추출 용이성, 구조화 데이터 중심",
          "SEO는 '클릭을 유도', GEO는 'AI가 대신 인용하고 요약'",
        ] },
        { t: "quote", x: "상위 10위에 드는 것과, AI 답변의 인용 자리에 드는 것은 완전히 다른 게임입니다." },
        { t: "cta" },
        { t: "h2", x: "왜 지금 중요한가" },
        { t: "p", x: "생성형 검색 사용이 빠르게 늘고 있습니다. AI가 당신을 언급하지 않으면, 사용자 입장에서 당신의 브랜드는 <b>존재하지 않는 것</b>과 다름없습니다. 반대로 초기에 GEO를 적용한 사이트는 경쟁이 덜한 지금 그 인용 자리를 선점할 수 있습니다." },
        { t: "h2", x: "무엇부터 해야 하나" },
        { t: "ol", items: [
          "핵심 질문에 첫 문단에서 바로 답하는 '답변 우선' 구조로 바꾸기",
          "주장에 수치·출처·인용을 붙여 사실 밀도 높이기",
          "AI 크롤러가 읽을 수 있도록 robots.txt와 렌더링 점검하기",
          "JSON-LD 구조화 데이터로 개체와 맥락을 기계에 전달하기",
        ] },
        { t: "p", x: "이 네 가지만 손봐도 인용 가능성은 눈에 띄게 올라갑니다. 문제는 '내 페이지가 지금 몇 점인지, 무엇부터 고쳐야 하는지'를 아는 것입니다. GeoScore는 바로 그것을 점수와 처방으로 알려줍니다." },
      ],
    },
    en: {
      title: "What Is GEO: The New Search Optimization for the AI Era",
      description:
        "What GEO (Generative Engine Optimization) means, how it differs from SEO, and why getting AI to cite your page is now tied directly to business survival.",
      category: "Basics",
      readMins: 6,
      blocks: [
        { t: "p", x: "The way people find information is changing at its core. We're moving from typing keywords and scanning ten links to asking ChatGPT, Perplexity or Gemini and getting <b>one synthesized answer</b>. That shift hands everyone who runs a website a brand-new challenge." },
        { t: "h2", x: "Defining GEO" },
        { t: "p", x: "<b>GEO (Generative Engine Optimization)</b> is the practice of optimizing your content and technical signals so that generative AI <b>cites your page as a trusted source</b> when it answers. A citation is a powerful recommendation in itself, and users click through from the cited source to your site." },
        { t: "h2", x: "How it differs from SEO" },
        { t: "p", x: "SEO is a game of <b>ranking</b> on the results page — the goal is the top 10. GEO is a game of landing in the <b>narrow citation slot</b> of an AI-generated answer, which typically names only a handful of domains as sources." },
        { t: "ul", items: [
          "SEO: keywords, backlinks, search ranking",
          "GEO: fact density, citability, extractability, structured data",
          "SEO earns the click; GEO gets the AI to cite and summarize you",
        ] },
        { t: "quote", x: "Ranking in the top 10 and landing in an AI answer's citation slot are two entirely different games." },
        { t: "cta" },
        { t: "h2", x: "Why it matters now" },
        { t: "p", x: "Generative search is growing fast. If the AI never mentions you, your brand is effectively <b>invisible</b> to the user. Sites that adopt GEO early can claim those citation slots while competition is still low." },
        { t: "h2", x: "Where to start" },
        { t: "ol", items: [
          "Rewrite to an 'answer-first' structure that answers the core question in the opening paragraph",
          "Raise fact density by backing claims with numbers, sources and quotes",
          "Check robots.txt and rendering so AI crawlers can actually read you",
          "Use JSON-LD structured data to convey entities and context to machines",
        ] },
        { t: "p", x: "Fixing just these four moves the needle noticeably. The hard part is knowing your page's current score and what to fix first — which is exactly what GeoScore turns into a score and a prescription." },
      ],
    },
  },
  {
    slug: "how-ai-chooses-sources",
    date: "2026-08-02",
    ko: {
      title: "AI가 인용하는 콘텐츠의 7가지 특징",
      description:
        "ChatGPT와 Perplexity 같은 생성형 엔진이 어떤 페이지를 출처로 고르는지, 실제로 인용되는 콘텐츠가 공유하는 7가지 특징을 정리했습니다.",
      category: "방법론",
      readMins: 7,
      blocks: [
        { t: "p", x: "생성형 엔진은 아무 페이지나 인용하지 않습니다. '기계가 읽고, 신뢰하고, 그대로 발췌하기 좋은' 콘텐츠를 선호하죠. 실제로 인용되는 페이지들이 공유하는 7가지 특징을 살펴봅니다." },
        { t: "h2", x: "1. 답변 우선 구조" },
        { t: "p", x: "첫 200단어 안에 핵심 질문에 대한 직답이 있어야 합니다. 브랜드 스토리로 시작하는 페이지는 AI가 발췌할 '답'을 찾지 못해 지나칩니다." },
        { t: "h2", x: "2. 높은 사실 밀도" },
        { t: "p", x: "수치, 통계, 날짜, 고유명사가 촘촘한 콘텐츠는 인용 가치가 높습니다. '빠르다' 대신 '평균 응답 200ms'처럼 검증 가능한 사실을 쓰세요." },
        { t: "h2", x: "3. 명확한 출처와 인용" },
        { t: "p", x: "주장에 출처를 붙이면 AI가 그 주장을 신뢰하고 재인용하기 쉬워집니다. 1차 자료 링크와 전문가 인용구는 특히 강력합니다." },
        { t: "h2", x: "4. 추출 가능한 청크 구조" },
        { t: "p", x: "명확한 소제목, 짧은 문단, 목록은 AI가 특정 조각을 깔끔하게 떼어 인용하도록 돕습니다. 하나의 거대한 문단은 인용되기 어렵습니다." },
        { t: "cta" },
        { t: "h2", x: "5. 질문 커버리지" },
        { t: "p", x: "사용자가 실제로 던지는 질문(누가·언제·왜·어떻게)을 페이지가 다루고 있어야 합니다. 관련 질문을 폭넓게 커버할수록 다양한 프롬프트에 매칭됩니다." },
        { t: "h2", x: "6. 최신성 신호" },
        { t: "p", x: "명시적인 게시일·수정일, 최근 데이터는 '지금도 유효한 정보'라는 신호를 줍니다. 오래된 페이지는 후순위로 밀립니다." },
        { t: "h2", x: "7. 저자 권위(E-E-A-T)" },
        { t: "p", x: "저자 정보, 경험, 전문성이 드러나면 신뢰도가 올라갑니다. 익명의 페이지보다 실명 전문가의 페이지가 인용에 유리합니다." },
        { t: "p", x: "일곱 가지를 한 번에 점검하기는 쉽지 않습니다. GeoScore는 이 항목들을 포함한 15개 루브릭으로 페이지를 자동 채점하고, 부족한 항목마다 고칠 문장을 제안합니다." },
      ],
    },
    en: {
      title: "7 Traits of Content That AI Cites",
      description:
        "How generative engines like ChatGPT and Perplexity pick their sources — the seven traits shared by pages that actually get cited.",
      category: "Methods",
      readMins: 7,
      blocks: [
        { t: "p", x: "Generative engines don't cite just any page. They favor content that is easy for a machine to read, trust and quote verbatim. Here are seven traits shared by pages that actually get cited." },
        { t: "h2", x: "1. Answer-first structure" },
        { t: "p", x: "The first 200 words must directly answer the core question. Pages that open with a brand story get skipped because the AI can't find an answer to extract." },
        { t: "h2", x: "2. High fact density" },
        { t: "p", x: "Content packed with numbers, statistics, dates and proper nouns is more citable. Write 'averages 200ms response time' instead of 'fast' — verifiable facts win." },
        { t: "h2", x: "3. Clear sources and citations" },
        { t: "p", x: "Attaching sources to claims makes the AI more willing to trust and re-cite them. Links to primary sources and expert quotes are especially strong." },
        { t: "h2", x: "4. Extractable chunk structure" },
        { t: "p", x: "Clear subheadings, short paragraphs and lists help the AI lift a clean fragment to quote. One giant paragraph is hard to cite." },
        { t: "cta" },
        { t: "h2", x: "5. Question coverage" },
        { t: "p", x: "Your page should address the real questions users ask (who, when, why, how). The more related questions you cover, the more prompts you can match." },
        { t: "h2", x: "6. Freshness signals" },
        { t: "p", x: "Explicit publish/modified dates and recent data signal that the information is still valid. Stale pages get deprioritized." },
        { t: "h2", x: "7. Author authority (E-E-A-T)" },
        { t: "p", x: "Visible author info, experience and expertise raise trust. A named expert's page beats an anonymous one for citations." },
        { t: "p", x: "Checking all seven at once isn't easy. GeoScore auto-scores your page against a 15-item rubric that includes these, and suggests the exact sentence to fix for each weak item." },
      ],
    },
  },
  {
    slug: "robots-txt-ai-crawlers",
    date: "2026-08-03",
    ko: {
      title: "robots.txt와 AI 크롤러: 당신의 페이지는 읽히고 있나요?",
      description:
        "GPTBot·ClaudeBot·PerplexityBot 등 AI 크롤러의 접근을 robots.txt가 막고 있지는 않은지, 그리고 어떻게 열어줘야 하는지 실무적으로 정리합니다.",
      category: "기술",
      readMins: 6,
      blocks: [
        { t: "p", x: "아무리 좋은 콘텐츠도 AI 크롤러가 읽지 못하면 인용될 수 없습니다. 가장 흔한 실수는 <b>robots.txt가 AI 봇을 차단</b>하고 있는 것입니다. 많은 사이트가 이 사실조차 모릅니다." },
        { t: "h2", x: "AI 크롤러란" },
        { t: "p", x: "생성형 엔진들은 각자의 크롤러로 웹을 수집합니다. 대표적으로 다음과 같습니다." },
        { t: "ul", items: [
          "GPTBot — OpenAI(ChatGPT)",
          "ClaudeBot / anthropic-ai — Anthropic(Claude)",
          "PerplexityBot — Perplexity",
          "Google-Extended — Google 생성형 AI",
        ] },
        { t: "h2", x: "차단되어 있는지 확인하는 법" },
        { t: "p", x: "당신 도메인의 <b>/robots.txt</b>를 열어 위 봇들에 대한 <b>Disallow</b> 규칙이 있는지 확인하세요. 보안·저작권 이유로 의도적으로 막았을 수도 있지만, 인용 노출을 원한다면 접근을 허용해야 합니다." },
        { t: "quote", x: "robots.txt 한 줄이 AI 인용의 문을 통째로 닫아버릴 수 있습니다." },
        { t: "cta" },
        { t: "h2", x: "허용하는 예시" },
        { t: "p", x: "특정 봇을 허용하려면 robots.txt에 명시적으로 규칙을 둘 수 있습니다. 예:" },
        { t: "ul", items: [
          "User-agent: GPTBot / Allow: /",
          "User-agent: PerplexityBot / Allow: /",
          "민감한 경로만 선택적으로 Disallow로 보호",
        ] },
        { t: "h2", x: "렌더링도 함께 봐야 합니다" },
        { t: "p", x: "크롤러가 접근할 수 있어도, 본문이 자바스크립트로만 그려진다면(클라이언트 렌더링) 봇이 빈 페이지를 볼 수 있습니다. 핵심 콘텐츠는 서버 렌더링(SSR)으로 raw HTML에 담겨야 안전합니다." },
        { t: "p", x: "GeoScore는 GPTBot·ClaudeBot·PerplexityBot 등 7종 크롤러의 접근성과 렌더링(SSR) 여부를 자동 판정하고, robots.txt 처방 스니펫까지 만들어 줍니다." },
      ],
    },
    en: {
      title: "robots.txt and AI Crawlers: Is Your Page Even Being Read?",
      description:
        "Whether your robots.txt is blocking AI crawlers like GPTBot, ClaudeBot and PerplexityBot — and how to open the door, in practical terms.",
      category: "Technical",
      readMins: 6,
      blocks: [
        { t: "p", x: "Even great content can't be cited if AI crawlers can't read it. The most common mistake is a <b>robots.txt that blocks AI bots</b> — and many sites don't even realize it." },
        { t: "h2", x: "What AI crawlers are" },
        { t: "p", x: "Generative engines collect the web with their own crawlers. The main ones include:" },
        { t: "ul", items: [
          "GPTBot — OpenAI (ChatGPT)",
          "ClaudeBot / anthropic-ai — Anthropic (Claude)",
          "PerplexityBot — Perplexity",
          "Google-Extended — Google generative AI",
        ] },
        { t: "h2", x: "How to check if you're blocked" },
        { t: "p", x: "Open your domain's <b>/robots.txt</b> and look for <b>Disallow</b> rules targeting those bots. You may have blocked them on purpose for security or copyright reasons, but if you want citation exposure you must allow access." },
        { t: "quote", x: "A single line in robots.txt can slam the door on AI citations entirely." },
        { t: "cta" },
        { t: "h2", x: "An example of allowing them" },
        { t: "p", x: "To allow specific bots, add explicit rules to robots.txt. For example:" },
        { t: "ul", items: [
          "User-agent: GPTBot / Allow: /",
          "User-agent: PerplexityBot / Allow: /",
          "Protect only sensitive paths with a targeted Disallow",
        ] },
        { t: "h2", x: "Rendering matters too" },
        { t: "p", x: "Even with access, if your body is drawn only by JavaScript (client rendering), the bot may see an empty page. Core content should ship in raw HTML via server-side rendering (SSR) to be safe." },
        { t: "p", x: "GeoScore automatically judges accessibility for 7 crawlers including GPTBot, ClaudeBot and PerplexityBot, checks SSR rendering, and even generates a robots.txt prescription snippet." },
      ],
    },
  },
  {
    slug: "json-ld-for-ai-citations",
    date: "2026-08-04",
    ko: {
      title: "JSON-LD 구조화 데이터로 AI 인용률 높이기",
      description:
        "구조화 데이터(JSON-LD)가 왜 AI 인용에 중요한지, 어떤 스키마를 어떻게 넣어야 하는지 복붙 가능한 예시와 함께 설명합니다.",
      category: "기술",
      readMins: 6,
      blocks: [
        { t: "p", x: "사람은 문맥으로 의미를 파악하지만, 기계는 명시적인 신호를 좋아합니다. <b>JSON-LD 구조화 데이터</b>는 '이 페이지가 무엇에 관한 것이고, 저자는 누구이며, 언제 작성됐는지'를 기계가 오해 없이 읽도록 알려주는 라벨입니다." },
        { t: "h2", x: "왜 인용에 도움이 되나" },
        { t: "p", x: "AI는 개체(회사·제품·인물)와 맥락을 정확히 이해할수록 안심하고 인용합니다. 구조화 데이터는 제목, 저자, 발행일, 제품 정보 같은 핵심 사실을 <b>추측이 아닌 선언</b>으로 전달합니다." },
        { t: "h2", x: "가장 많이 쓰는 스키마" },
        { t: "ul", items: [
          "Article / BlogPosting — 글·아티클",
          "Product / Offer — 제품·가격",
          "Organization — 브랜드 개체 정의",
          "FAQPage — 질문·답변",
          "BreadcrumbList — 사이트 구조",
        ] },
        { t: "cta" },
        { t: "h2", x: "복붙 예시 (Article)" },
        { t: "p", x: "글 페이지라면 <head>에 다음과 같은 JSON-LD를 넣습니다. 값을 실제 정보로 바꾸기만 하면 됩니다." },
        { t: "ul", items: [
          '@type: "Article"',
          'headline: 글 제목',
          'author: { @type: "Person", name: 저자명 }',
          'datePublished / dateModified: 발행·수정일',
        ] },
        { t: "h2", x: "흔한 실수" },
        { t: "p", x: "스키마를 넣었지만 본문 내용과 일치하지 않거나, 날짜가 오래됐거나, 필수 필드가 비어 있으면 오히려 신뢰를 잃습니다. 구조화 데이터는 <b>정확하고 최신</b>이어야 합니다." },
        { t: "p", x: "GeoScore는 페이지의 JSON-LD를 직접 읽어 존재 여부와 정합성을 점검하고, 없다면 바로 붙여넣을 수 있는 스키마 스니펫을 생성합니다." },
      ],
    },
    en: {
      title: "Raise Your AI Citation Rate with JSON-LD Structured Data",
      description:
        "Why structured data (JSON-LD) matters for AI citations, and which schemas to add and how — with copy-paste examples.",
      category: "Technical",
      readMins: 6,
      blocks: [
        { t: "p", x: "Humans infer meaning from context, but machines love explicit signals. <b>JSON-LD structured data</b> is a label that tells machines, without ambiguity, what a page is about, who wrote it and when." },
        { t: "h2", x: "Why it helps with citations" },
        { t: "p", x: "The more precisely AI understands the entities (companies, products, people) and context, the more confidently it cites. Structured data conveys key facts — title, author, publish date, product info — as <b>declarations, not guesses</b>." },
        { t: "h2", x: "The most-used schemas" },
        { t: "ul", items: [
          "Article / BlogPosting — posts and articles",
          "Product / Offer — products and pricing",
          "Organization — defining your brand entity",
          "FAQPage — questions and answers",
          "BreadcrumbList — site structure",
        ] },
        { t: "cta" },
        { t: "h2", x: "Copy-paste example (Article)" },
        { t: "p", x: "For an article page, add JSON-LD like the following in <head>. Just replace the values with your real information." },
        { t: "ul", items: [
          '@type: "Article"',
          "headline: the article title",
          'author: { @type: "Person", name: author }',
          "datePublished / dateModified: publish and update dates",
        ] },
        { t: "h2", x: "Common mistakes" },
        { t: "p", x: "If the schema doesn't match the body, the dates are stale, or required fields are empty, you actually lose trust. Structured data must be <b>accurate and current</b>." },
        { t: "p", x: "GeoScore reads your page's JSON-LD directly to check presence and consistency, and if it's missing, generates a schema snippet you can paste right in." },
      ],
    },
  },
  {
    slug: "cep-strategy",
    date: "2026-08-05",
    ko: {
      title: "CEP 전략: 제품 중심에서 상황 중심으로",
      description:
        "사용자가 AI에게 던지는 실제 상황(상황 진입점, CEP)에 맞춰 콘텐츠를 재구성하면 인용률이 오릅니다. Before/After 예시로 방법을 보여줍니다.",
      category: "전략",
      readMins: 7,
      blocks: [
        { t: "p", x: "많은 페이지가 '제품이 무엇인지'만 설명합니다. 하지만 사용자는 AI에게 <b>자신의 상황</b>을 말하며 묻습니다. 이 간극을 메우는 것이 CEP 전략입니다." },
        { t: "h2", x: "CEP란 무엇인가" },
        { t: "p", x: "<b>CEP(Category Entry Point, 상황 진입점)</b>는 사용자가 어떤 카테고리를 떠올리게 되는 구체적 상황입니다. 누가·언제·왜·어떤 제약과 기준으로 그 니즈가 생기는가를 말합니다." },
        { t: "p", x: "예를 들어 커피 원두를 판다면, 사용자는 '아라비카 원두'가 아니라 <b>'야근할 때 집중 잘 되는 커피'</b>라고 묻습니다. AI는 후자의 언어에 답하려 하죠." },
        { t: "h2", x: "Before → After" },
        { t: "p", x: "<b>Before:</b> 고농도 아라비카 원두를 사용합니다. (제품 스펙 중심)" },
        { t: "p", x: "<b>After:</b> 야근처럼 집중이 필요한 순간을 위해 100ml당 카페인 12mg을 담았습니다. (상황 + 검증 가능한 근거)" },
        { t: "cta" },
        { t: "h2", x: "CEP를 찾는 법" },
        { t: "ol", items: [
          "타깃 고객이 이 제품을 떠올리는 순간 6~8개를 나열한다",
          "각 순간을 '누가·언제·왜·기준'으로 구체화한다",
          "각 상황에 대해 실제로 던질 법한 질문을 적어본다",
          "그 질문에 직답하는 문장과 근거(수치·출처)를 페이지에 추가한다",
        ] },
        { t: "h2", x: "왜 인용률이 오르나" },
        { t: "p", x: "상황 언어로 쓰인 콘텐츠는 사용자의 실제 프롬프트와 매칭될 확률이 높습니다. 게다가 각 상황에 근거(수치·출처)를 붙이면 사실 밀도까지 올라가 인용 가치가 두 배가 됩니다." },
        { t: "p", x: "GeoScore는 페이지 기준으로 CEP를 6~8개 도출하고 각 상황의 대응도(충분·부분·미대응)를 평가하며, 제품 중심 문장을 상황 중심으로 재작성해 줍니다." },
      ],
    },
    en: {
      title: "The CEP Strategy: From Product-Centric to Situation-Centric",
      description:
        "Restructuring content around the real situations users bring to AI (Category Entry Points) raises citation rates. We show how with before/after examples.",
      category: "Strategy",
      readMins: 7,
      blocks: [
        { t: "p", x: "Many pages only explain 'what the product is.' But users describe <b>their own situation</b> when they ask an AI. Bridging that gap is what the CEP strategy is about." },
        { t: "h2", x: "What a CEP is" },
        { t: "p", x: "A <b>CEP (Category Entry Point)</b> is the concrete situation that makes a user think of a category — who, when, why, and under what constraints and criteria the need arises." },
        { t: "p", x: "If you sell coffee beans, users don't ask for 'Arabica beans' — they ask for <b>'coffee that helps me focus during late-night work.'</b> The AI tries to answer in that latter language." },
        { t: "h2", x: "Before → After" },
        { t: "p", x: "<b>Before:</b> We use high-concentration Arabica beans. (product-spec centric)" },
        { t: "p", x: "<b>After:</b> For moments that demand focus, like late-night work, we packed in 12mg of caffeine per 100ml. (situation + verifiable evidence)" },
        { t: "cta" },
        { t: "h2", x: "How to find your CEPs" },
        { t: "ol", items: [
          "List 6–8 moments when your target customer thinks of this product",
          "Make each moment concrete with who/when/why/criteria",
          "Write the questions a user would realistically ask in each",
          "Add sentences that directly answer them, backed by evidence (numbers, sources)",
        ] },
        { t: "h2", x: "Why citation rates rise" },
        { t: "p", x: "Situation-worded content is far more likely to match a user's actual prompt. And attaching evidence (numbers, sources) to each situation raises fact density too — doubling your citation value." },
        { t: "p", x: "GeoScore derives 6–8 CEPs for your page, rates coverage for each (full, partial, not addressed), and rewrites product-centric sentences into situation-centric ones." },
      ],
    },
  },
  {
    slug: "ecommerce-geo",
    date: "2026-08-06",
    ko: {
      title: "이커머스 GEO: 제품 페이지가 AI 추천에 오르는 법",
      description:
        "쇼핑몰·브랜드 스토어의 제품 페이지가 ChatGPT·Perplexity의 '추천 목록'에 인용되게 만드는 실전 GEO 전략을 정리합니다.",
      category: "업종별 · 이커머스",
      readMins: 7,
      blocks: [
        { t: "p", x: "\"20만원대 조용한 무선 청소기 추천해줘\" — 소비자는 이제 이렇게 AI에게 묻습니다. 그리고 AI는 몇 개 제품만 골라 추천하죠. 당신의 제품이 그 목록에 들지 못하면, 아무리 좋은 상품도 팔리지 않습니다." },
        { t: "h2", x: "제품 페이지의 가장 큰 문제" },
        { t: "p", x: "대부분의 상세페이지는 <b>이미지와 브랜드 스토리</b>로 시작합니다. 하지만 AI는 이미지를 인용하지 못합니다. 스펙·수치·비교 정보가 <b>텍스트로</b> 있어야 인용됩니다." },
        { t: "ul", items: [
          "핵심 스펙(크기·무게·용량·소음 dB·배터리 시간)을 텍스트로 명시",
          "'조용하다' 대신 '작동 소음 58dB'처럼 수치화",
          "가격대·용도·대상 고객을 문장으로 서술",
        ] },
        { t: "h2", x: "상황 언어로 쓰기 (CEP)" },
        { t: "p", x: "소비자는 '무선 청소기'가 아니라 <b>'아기 있는 집에서 쓸 조용한 청소기'</b>라고 묻습니다. 제품이 어떤 <b>상황</b>에 맞는지를 페이지에 담으면 훨씬 많은 질문에 매칭됩니다." },
        { t: "quote", x: "AI는 제품 스펙이 아니라, 고객의 상황에 답하려 합니다." },
        { t: "cta" },
        { t: "h2", x: "리뷰와 근거를 활용하라" },
        { t: "p", x: "별점 평균, 리뷰 수, 재구매율 같은 <b>검증 가능한 사회적 증거</b>는 AI가 신뢰하고 인용하기 좋은 재료입니다. 구조화 데이터(Product·Offer·AggregateRating)로 함께 표기하세요." },
        { t: "h2", x: "기술 체크리스트" },
        { t: "ol", items: [
          "robots.txt가 GPTBot·PerplexityBot을 막고 있지 않은지 확인",
          "가격·재고·본문이 SSR로 raw HTML에 담기는지 확인(JS 전용 렌더링 주의)",
          "Product/Offer/AggregateRating JSON-LD 추가",
          "제품명·개체를 명확히 하는 도입부 블록 작성",
        ] },
        { t: "p", x: "GeoScore로 제품 페이지를 진단하면 이 항목들을 점수로 보여주고, '이 문장을 이렇게 바꾸라'는 처방까지 받을 수 있습니다. 판매 페이지 하나하나가 AI 추천 후보가 됩니다." },
      ],
    },
    en: {
      title: "E-commerce GEO: Getting Product Pages into AI Recommendations",
      description:
        "Practical GEO strategies to make your store's product pages get cited in the 'recommended' lists of ChatGPT and Perplexity.",
      category: "Industry · E-commerce",
      readMins: 7,
      blocks: [
        { t: "p", x: "\"Recommend a quiet cordless vacuum under $200\" — that's how shoppers ask AI now, and the AI picks just a few products. If yours isn't on that list, even a great product won't sell." },
        { t: "h2", x: "The biggest problem with product pages" },
        { t: "p", x: "Most product pages open with <b>images and a brand story</b>. But AI can't cite images. Specs, numbers and comparisons must be present <b>as text</b> to be cited." },
        { t: "ul", items: [
          "State key specs (size, weight, capacity, noise dB, battery life) as text",
          "Quantify: '58dB operating noise' instead of 'quiet'",
          "Describe price tier, use case and target customer in sentences",
        ] },
        { t: "h2", x: "Write in situation language (CEP)" },
        { t: "p", x: "Shoppers don't ask for a 'cordless vacuum' — they ask for a <b>'quiet vacuum for a home with a baby.'</b> Capturing which <b>situation</b> your product fits matches far more queries." },
        { t: "quote", x: "AI answers the customer's situation, not your product's spec sheet." },
        { t: "cta" },
        { t: "h2", x: "Leverage reviews and evidence" },
        { t: "p", x: "Average rating, review count and repurchase rate are <b>verifiable social proof</b> that AI trusts and cites. Mark them up with structured data (Product, Offer, AggregateRating)." },
        { t: "h2", x: "Technical checklist" },
        { t: "ol", items: [
          "Confirm robots.txt doesn't block GPTBot / PerplexityBot",
          "Ensure price, stock and body ship in raw HTML via SSR (watch JS-only rendering)",
          "Add Product / Offer / AggregateRating JSON-LD",
          "Write an intro block that makes the product name and entity clear",
        ] },
        { t: "p", x: "Run a product page through GeoScore and it scores these items and prescribes exactly which sentence to change — turning each sales page into a candidate for AI recommendations." },
      ],
    },
  },
  {
    slug: "saas-geo",
    date: "2026-08-06",
    ko: {
      title: "SaaS GEO: AI가 당신의 툴을 추천하게 만드는 법",
      description:
        "\"~하는 데 좋은 툴 추천\"이라는 질문에 AI가 당신의 SaaS를 인용하게 만드는 콘텐츠·문서 전략을 다룹니다.",
      category: "업종별 · SaaS",
      readMins: 7,
      blocks: [
        { t: "p", x: "B2B 구매의 첫 단계가 '검색'에서 'AI에게 묻기'로 옮겨가고 있습니다. \"팀 일정 관리에 좋은 툴 뭐 있어?\"라는 질문에 AI가 당신의 제품을 언급하는지가 파이프라인을 좌우합니다." },
        { t: "h2", x: "기능이 아니라 '해결하는 문제'를 써라" },
        { t: "p", x: "많은 SaaS 페이지가 기능 목록만 나열합니다. AI는 <b>'어떤 문제를 어떻게 해결하는가'</b>를 이해해야 추천합니다. 유스케이스별로 명확한 문장을 두세요." },
        { t: "ul", items: [
          "\"~하는 팀을 위한\", \"~할 때 쓰는\" 같은 상황·대상 서술",
          "경쟁 대안 대비 차별점을 검증 가능한 사실로",
          "가격·플랜·무료 체험 여부를 텍스트로 명시",
        ] },
        { t: "h2", x: "문서(Docs)가 최고의 GEO 자산" },
        { t: "p", x: "잘 정리된 도움말·가이드 문서는 AI가 특히 좋아하는 인용 대상입니다. 구체적 질문에 직답하는 <b>답변 우선 구조</b>로 작성하고, 코드·설정 예시를 포함하세요." },
        { t: "quote", x: "훌륭한 문서는 지원 비용을 줄이는 동시에, AI 인용의 가장 강력한 무기가 됩니다." },
        { t: "cta" },
        { t: "h2", x: "비교·대안 콘텐츠 만들기" },
        { t: "p", x: "\"A 대안\", \"A vs B\" 같은 비교 질문은 구매 직전 단계입니다. 공정하고 사실에 근거한 비교 페이지를 두면, 그 결정적 순간에 AI가 당신을 인용할 확률이 높아집니다." },
        { t: "h2", x: "기술 위생" },
        { t: "ol", items: [
          "마케팅 페이지·문서가 SSR로 크롤러에 읽히는지 확인",
          "SoftwareApplication/Product JSON-LD로 제품 개체 정의",
          "llms.txt로 핵심 페이지를 안내",
          "변경 로그·날짜로 최신성 신호 유지",
        ] },
        { t: "p", x: "GeoScore로 랜딩·문서·비교 페이지를 각각 진단해 인용 준비도를 점검하세요. 어떤 페이지가 AI 추천에 약한지 한눈에 보입니다." },
      ],
    },
    en: {
      title: "SaaS GEO: Getting AI to Recommend Your Tool",
      description:
        "Content and docs strategies that get AI to cite your SaaS when someone asks for 'a good tool to do X'.",
      category: "Industry · SaaS",
      readMins: 7,
      blocks: [
        { t: "p", x: "The first step of B2B buying is shifting from 'search' to 'ask an AI'. Whether the AI mentions your product for \"what's a good tool for team scheduling?\" now shapes your pipeline." },
        { t: "h2", x: "Write the problem you solve, not just features" },
        { t: "p", x: "Many SaaS pages just list features. AI recommends only when it understands <b>which problem you solve and how</b>. Add clear sentences per use case." },
        { t: "ul", items: [
          "Describe situation/audience: 'for teams that…', 'used when…'",
          "State differentiation vs. alternatives as verifiable facts",
          "Spell out pricing, plans and free trial as text",
        ] },
        { t: "h2", x: "Docs are your best GEO asset" },
        { t: "p", x: "Well-structured help and guide docs are a favorite citation target for AI. Write in an <b>answer-first structure</b> that directly answers specific questions, and include code/config examples." },
        { t: "quote", x: "Great docs cut support costs and double as the most powerful weapon for AI citations." },
        { t: "cta" },
        { t: "h2", x: "Create comparison and alternative content" },
        { t: "p", x: "Comparison queries like 'A alternative' or 'A vs B' are right before purchase. A fair, fact-based comparison page raises the odds the AI cites you at that decisive moment." },
        { t: "h2", x: "Technical hygiene" },
        { t: "ol", items: [
          "Confirm marketing pages and docs render via SSR for crawlers",
          "Define the product entity with SoftwareApplication / Product JSON-LD",
          "Point to key pages with llms.txt",
          "Keep freshness signals with changelogs and dates",
        ] },
        { t: "p", x: "Use GeoScore to score your landing, docs and comparison pages separately for citation-readiness — you'll see at a glance which pages are weak for AI recommendations." },
      ],
    },
  },
  {
    slug: "local-business-geo",
    date: "2026-07-30",
    ko: {
      title: "로컬 비즈니스·병원 GEO: '내 근처' AI 추천 잡기",
      description:
        "치과·미용실·카페·병원 등 지역 기반 사업이 \"근처 ~ 추천\" 질문에서 AI에 인용되도록 하는 로컬 GEO 전략입니다.",
      category: "업종별 · 로컬",
      readMins: 6,
      blocks: [
        { t: "p", x: "\"강남역 근처 야간 진료 치과 알려줘\" — 로컬 소비자의 결정적 순간입니다. 이 질문에 AI가 당신을 언급하면 곧바로 방문·예약으로 이어집니다." },
        { t: "h2", x: "위치·시간·서비스를 명확히" },
        { t: "p", x: "AI가 로컬 추천을 하려면 <b>어디에, 언제, 무엇을</b> 제공하는지가 텍스트로 분명해야 합니다." },
        { t: "ul", items: [
          "정확한 주소·지역명·랜드마크 언급(예: 강남역 3번 출구 도보 2분)",
          "영업시간·야간/주말 진료·휴무일 명시",
          "제공 서비스와 특화 분야를 구체적으로",
        ] },
        { t: "h2", x: "LocalBusiness 구조화 데이터" },
        { t: "p", x: "LocalBusiness(또는 업종별 하위 타입) JSON-LD로 상호·주소·전화·영업시간·좌표를 선언하면 기계가 오해 없이 읽습니다. 병원이면 MedicalClinic, 음식점이면 Restaurant 타입을 사용하세요." },
        { t: "quote", x: "로컬 GEO의 핵심은 '어디·언제·무엇'을 기계가 읽을 수 있게 만드는 것입니다." },
        { t: "cta" },
        { t: "h2", x: "실제 질문에 답하는 FAQ" },
        { t: "p", x: "\"주차 되나요?\", \"보험 적용되나요?\", \"예약 없이 가도 되나요?\" 같은 실제 질문을 FAQPage로 담으면, AI가 그 답을 그대로 인용하기 좋습니다." },
        { t: "h2", x: "신뢰 신호" },
        { t: "ol", items: [
          "리뷰·평점을 텍스트와 구조화 데이터로 함께",
          "자격·경력·인증 등 전문성(E-E-A-T) 노출",
          "최신 공지·진료 변경 사항으로 최신성 유지",
        ] },
        { t: "p", x: "홈페이지가 있다면 GeoScore로 진단해 '근처 추천' 질문에 얼마나 준비됐는지 점수로 확인하세요. 로컬 검색이 AI로 넘어가는 지금이 선점 기회입니다." },
      ],
    },
    en: {
      title: "Local Business & Clinic GEO: Winning 'Near Me' AI Recommendations",
      description:
        "Local GEO strategies so dentists, salons, cafes and clinics get cited by AI for 'recommend a ~ near me' questions.",
      category: "Industry · Local",
      readMins: 6,
      blocks: [
        { t: "p", x: "\"Find a dentist near Gangnam Station open at night\" — a decisive moment for a local shopper. If the AI names you here, it turns straight into a visit or booking." },
        { t: "h2", x: "Make location, hours and services clear" },
        { t: "p", x: "For AI to recommend you locally, <b>where, when and what</b> you offer must be clear in text." },
        { t: "ul", items: [
          "Mention exact address, area and landmarks (e.g., 2-min walk from Exit 3)",
          "State hours, night/weekend availability and days off",
          "Describe services and specialties specifically",
        ] },
        { t: "h2", x: "LocalBusiness structured data" },
        { t: "p", x: "Declare name, address, phone, hours and coordinates with LocalBusiness JSON-LD (or a subtype). Use MedicalClinic for clinics, Restaurant for eateries, so machines read it unambiguously." },
        { t: "quote", x: "The heart of local GEO is making 'where, when, what' machine-readable." },
        { t: "cta" },
        { t: "h2", x: "An FAQ that answers real questions" },
        { t: "p", x: "Put real questions — 'Is parking available?', 'Do you take insurance?', 'Can I walk in?' — into an FAQPage, and AI can quote the answers directly." },
        { t: "h2", x: "Trust signals" },
        { t: "ol", items: [
          "Show reviews/ratings in both text and structured data",
          "Expose expertise (E-E-A-T): credentials, experience, certifications",
          "Keep freshness with recent notices and schedule changes",
        ] },
        { t: "p", x: "If you have a site, run it through GeoScore to see how ready it is for 'near me' questions. With local search moving to AI, now is the time to claim your spot." },
      ],
    },
  },
  {
    slug: "professional-services-geo",
    date: "2026-07-29",
    ko: {
      title: "전문 서비스 GEO: 법률·세무·컨설팅의 신뢰 기반 인용",
      description:
        "변호사·회계사·컨설턴트 등 전문 서비스가 신뢰와 전문성(E-E-A-T)을 무기로 AI 답변에 인용되게 하는 전략입니다.",
      category: "업종별 · 전문 서비스",
      readMins: 6,
      blocks: [
        { t: "p", x: "\"프리랜서 종합소득세 신고 어떻게 해?\" 같은 질문에 AI가 답할 때, 신뢰할 만한 전문가의 콘텐츠를 출처로 인용합니다. 전문 서비스에게 GEO는 곧 <b>권위의 증명</b>입니다." },
        { t: "h2", x: "전문성(E-E-A-T)을 드러내라" },
        { t: "p", x: "AI는 민감·전문 주제일수록 <b>저자의 자격</b>을 중시합니다. 익명 글보다 실명 전문가의 글이 인용에 유리합니다." },
        { t: "ul", items: [
          "저자의 자격·경력·소속을 명확히(변호사, 세무사 등)",
          "실무 경험과 사례를 구체적으로 서술",
          "관련 법·규정·기준의 출처를 정확히 인용",
        ] },
        { t: "h2", x: "질문에 직답하는 콘텐츠" },
        { t: "p", x: "잠재 고객의 실제 질문을 제목으로 삼고, 첫 문단에서 핵심을 요약한 뒤 상세를 전개하세요. 이 <b>답변 우선 구조</b>가 인용 확률을 크게 높입니다." },
        { t: "quote", x: "전문 서비스의 GEO는 '얼마나 신뢰할 수 있는가'를 기계가 알아보게 만드는 일입니다." },
        { t: "cta" },
        { t: "h2", x: "정확성과 최신성" },
        { t: "p", x: "법·세제는 자주 바뀝니다. 게시일·개정 반영일을 명시하고 오래된 정보는 갱신하세요. 부정확한 정보는 신뢰를 잃고 인용에서 배제됩니다." },
        { t: "h2", x: "구조화 데이터" },
        { t: "ol", items: [
          "Article/Person JSON-LD로 저자 전문성 표기",
          "FAQPage로 자주 묻는 법률·세무 질문 정리",
          "Organization으로 사무소 개체 정의",
        ] },
        { t: "p", x: "GeoScore는 저자 권위·출처 인용·최신성 같은 항목을 채점하므로, 전문 서비스 콘텐츠가 AI에 인용될 준비가 됐는지 정확히 진단할 수 있습니다." },
      ],
    },
    en: {
      title: "Professional Services GEO: Trust-Based Citations for Law, Tax & Consulting",
      description:
        "How lawyers, accountants and consultants use trust and expertise (E-E-A-T) to get cited in AI answers.",
      category: "Industry · Professional",
      readMins: 6,
      blocks: [
        { t: "p", x: "When AI answers a question like 'how do freelancers file income tax?', it cites content from trustworthy experts. For professional services, GEO is a <b>proof of authority</b>." },
        { t: "h2", x: "Show your expertise (E-E-A-T)" },
        { t: "p", x: "The more sensitive or specialized the topic, the more AI weighs the <b>author's credentials</b>. A named expert's piece beats an anonymous one for citations." },
        { t: "ul", items: [
          "State the author's qualifications, experience and affiliation clearly",
          "Describe hands-on experience and cases specifically",
          "Cite the exact source of relevant laws, rules and standards",
        ] },
        { t: "h2", x: "Content that answers directly" },
        { t: "p", x: "Use the client's real question as the title, summarize the key point in the first paragraph, then expand. This <b>answer-first structure</b> markedly raises citation odds." },
        { t: "quote", x: "GEO for professional services is making 'how trustworthy is this' legible to machines." },
        { t: "cta" },
        { t: "h2", x: "Accuracy and freshness" },
        { t: "p", x: "Laws and taxes change often. State publish and revision dates and update stale info. Inaccurate content loses trust and gets excluded from citations." },
        { t: "h2", x: "Structured data" },
        { t: "ol", items: [
          "Mark author expertise with Article / Person JSON-LD",
          "Organize common legal/tax questions with FAQPage",
          "Define the firm entity with Organization",
        ] },
        { t: "p", x: "GeoScore scores items like author authority, source citations and freshness, so you can precisely diagnose whether your professional content is ready to be cited by AI." },
      ],
    },
  },
  {
    slug: "content-media-geo",
    date: "2026-07-28",
    ko: {
      title: "블로그·미디어 GEO: 콘텐츠가 AI 답변의 출처가 되는 법",
      description:
        "블로그·뉴스·미디어 콘텐츠가 트래픽 감소 시대에 AI 답변의 인용 출처로 살아남는 GEO 전략을 다룹니다.",
      category: "업종별 · 미디어",
      readMins: 6,
      blocks: [
        { t: "p", x: "AI가 답을 요약해 주면서 '검색 후 클릭' 트래픽은 줄고 있습니다. 하지만 AI 답변의 <b>출처로 인용</b>되면 새로운 유입 경로가 열립니다. 미디어에게 GEO는 생존 전략입니다." },
        { t: "h2", x: "인용되기 쉬운 문장 만들기" },
        { t: "p", x: "AI는 명료하고 독립적으로 성립하는 문장을 발췌합니다. 하나의 핵심 사실을 담은 <b>짧고 자족적인 문장</b>이 긴 만연체보다 인용에 유리합니다." },
        { t: "ul", items: [
          "핵심 수치·결론을 별도 문장으로 분리",
          "소제목으로 주제를 명확히 청크화",
          "요약(TL;DR)·핵심 요점 박스 제공",
        ] },
        { t: "h2", x: "1차 정보와 데이터의 힘" },
        { t: "p", x: "직접 취재·조사·데이터가 담긴 콘텐츠는 대체 불가능한 인용 대상입니다. 남들이 재인용할 <b>원천 사실</b>을 만들면 AI도 당신을 출처로 지목합니다." },
        { t: "quote", x: "AI 시대엔 '요약 가능한 콘텐츠'보다 '인용할 수밖에 없는 원천 사실'이 이깁니다." },
        { t: "cta" },
        { t: "h2", x: "최신성과 저자" },
        { t: "p", x: "게시일·수정일을 명확히 하고, 기자·필자의 전문성을 드러내세요. 시의성 있는 주제일수록 최신성 신호가 인용 여부를 가릅니다." },
        { t: "h2", x: "기술 기반" },
        { t: "ol", items: [
          "AI 크롤러 접근 허용(robots.txt) 및 SSR 확인",
          "Article/NewsArticle JSON-LD와 저자·발행일 표기",
          "관련 글 내부 링크로 주제 권위 강화",
        ] },
        { t: "p", x: "GeoScore로 대표 콘텐츠를 진단하면, 어떤 글이 AI 인용에 강하고 약한지, 무엇을 고치면 좋을지 바로 알 수 있습니다." },
      ],
    },
    en: {
      title: "Blog & Media GEO: Becoming the Source Behind AI Answers",
      description:
        "GEO strategies for blogs, news and media to survive the traffic decline by becoming the cited source in AI answers.",
      category: "Industry · Media",
      readMins: 6,
      blocks: [
        { t: "p", x: "As AI summarizes answers, 'search-then-click' traffic is shrinking. But being <b>cited as a source</b> in AI answers opens a new inflow channel. For media, GEO is a survival strategy." },
        { t: "h2", x: "Write sentences that are easy to cite" },
        { t: "p", x: "AI lifts clear, self-contained sentences. A <b>short, standalone sentence</b> carrying one key fact is more citable than a long run-on." },
        { t: "ul", items: [
          "Separate key figures and conclusions into their own sentences",
          "Chunk topics clearly with subheadings",
          "Provide a TL;DR / key-takeaways box",
        ] },
        { t: "h2", x: "The power of primary data" },
        { t: "p", x: "Content with original reporting, research or data is an irreplaceable citation target. Create <b>source facts</b> others re-cite and AI will name you as the source." },
        { t: "quote", x: "In the AI era, 'irreplaceable source facts' beat merely 'summarizable content'." },
        { t: "cta" },
        { t: "h2", x: "Freshness and authorship" },
        { t: "p", x: "Make publish/modified dates clear and show the reporter's or writer's expertise. The more timely the topic, the more freshness decides whether you're cited." },
        { t: "h2", x: "Technical foundation" },
        { t: "ol", items: [
          "Allow AI crawlers (robots.txt) and confirm SSR",
          "Use Article / NewsArticle JSON-LD with author and publish date",
          "Reinforce topical authority with internal links to related posts",
        ] },
        { t: "p", x: "Diagnose your flagship posts with GeoScore to see which are strong or weak for AI citations, and exactly what to fix." },
      ],
    },
  },
  {
    slug: "real-estate-geo",
    date: "2026-08-07",
    ko: {
      title: "부동산 GEO: 매물·중개사무소가 AI 추천에 오르는 법",
      description:
        "\"~동에서 신혼집 전세 추천\" 같은 질문에 AI가 당신의 매물·중개사무소를 인용하게 만드는 부동산 GEO 전략을 정리합니다.",
      category: "업종별 · 부동산",
      readMins: 6,
      blocks: [
        { t: "p", x: "\"판교 근처 초등학교 가까운 아파트 전세 알려줘\" — 부동산 탐색도 AI로 넘어가고 있습니다. AI가 당신의 매물이나 중개사무소를 언급하는지가 문의로 직결됩니다." },
        { t: "h2", x: "매물 정보를 텍스트로, 구체적으로" },
        { t: "p", x: "사진 갤러리만 있는 매물 페이지는 AI가 읽지 못합니다. <b>위치·면적·층·방향·가격·관리비·입주 가능일</b>을 텍스트로 명확히 적어야 인용됩니다." },
        { t: "ul", items: [
          "정확한 지역·단지명·역세권·학군 정보 명시",
          "전용/공급 면적, 층수, 방향, 방/욕실 수를 수치로",
          "전세/월세/매매가와 관리비를 텍스트로",
        ] },
        { t: "h2", x: "생활 맥락(CEP)으로 쓰기" },
        { t: "p", x: "사람들은 '84㎡ 아파트'가 아니라 <b>'아이 키우기 좋은 조용한 집'</b>을 찾습니다. 학군·교통·조용함·채광 같은 <b>생활 상황</b>을 문장으로 담으면 훨씬 많은 질문에 매칭됩니다." },
        { t: "quote", x: "AI는 '평수'가 아니라 '어떤 삶에 맞는 집인가'에 답하려 합니다." },
        { t: "h2", x: "신뢰와 전문성" },
        { t: "p", x: "중개사무소라면 등록번호·경력·전문 지역·거래 실적을 드러내세요. 지역 전문성(E-E-A-T)이 분명할수록 AI가 안심하고 인용합니다." },
        { t: "h2", x: "기술 체크리스트" },
        { t: "ol", items: [
          "매물 본문이 SSR로 크롤러에 읽히는지 확인(지도·갤러리만 있으면 위험)",
          "RealEstateListing/LocalBusiness JSON-LD로 매물·사무소 개체 정의",
          "\"주차 되나요\", \"반려동물 가능한가요\" 같은 실제 질문을 FAQ로",
          "게시일·거래 상태로 최신성 유지",
        ] },
        { t: "p", x: "GeoScore로 매물·소개 페이지를 진단하면 '지역 추천' 질문에 얼마나 준비됐는지 점수로 확인하고, 부족한 문장까지 처방받을 수 있습니다." },
      ],
    },
    en: {
      title: "Real Estate GEO: Getting Listings & Agencies into AI Recommendations",
      description:
        "GEO strategies so AI cites your listings or agency for questions like 'recommend a starter-home lease in ~ neighborhood'.",
      category: "Industry · Real Estate",
      readMins: 6,
      blocks: [
        { t: "p", x: "\"Find an apartment near a good elementary school around Pangyo\" — property search is moving to AI too. Whether the AI mentions your listing or agency ties straight to inquiries." },
        { t: "h2", x: "Put listing details in text, specifically" },
        { t: "p", x: "A listing page that's just a photo gallery can't be read by AI. <b>Location, size, floor, orientation, price, maintenance fee and move-in date</b> must be clear in text to be cited." },
        { t: "ul", items: [
          "State exact area, complex name, nearby stations and school district",
          "Give net/gross area, floor, orientation, room/bath counts as numbers",
          "Put lease/rent/sale price and maintenance fee in text",
        ] },
        { t: "h2", x: "Write in life-context (CEP)" },
        { t: "p", x: "People don't look for an '84㎡ apartment' — they want a <b>'quiet home good for raising kids.'</b> Capturing <b>life situations</b> like schools, transit, quietness and light matches many more queries." },
        { t: "quote", x: "AI answers 'which life this home fits', not the square footage." },
        { t: "h2", x: "Trust and expertise" },
        { t: "p", x: "For an agency, show your license number, experience, specialty areas and track record. The clearer your local expertise (E-E-A-T), the more confidently AI cites you." },
        { t: "h2", x: "Technical checklist" },
        { t: "ol", items: [
          "Confirm listing text renders via SSR (a map/gallery-only page is risky)",
          "Define listing/agency entities with RealEstateListing / LocalBusiness JSON-LD",
          "Turn real questions ('parking?', 'pets allowed?') into an FAQ",
          "Keep freshness with publish date and deal status",
        ] },
        { t: "p", x: "Diagnose your listing and profile pages with GeoScore to see how ready they are for 'area recommendation' questions — down to the sentence to fix." },
      ],
    },
  },
  {
    slug: "education-geo",
    date: "2026-07-27",
    ko: {
      title: "교육 GEO: 강의·학원이 AI 추천에 인용되는 법",
      description:
        "온라인 강의·학원·교육 콘텐츠가 \"~ 배우기 좋은 강의 추천\" 질문에서 AI에 인용되도록 하는 교육 업종 GEO 전략입니다.",
      category: "업종별 · 교육",
      readMins: 6,
      blocks: [
        { t: "p", x: "\"비전공자가 데이터 분석 배우기 좋은 강의 추천해줘\" — 학습자는 AI에게 진로와 학습 경로를 묻습니다. 그 답에 당신의 강의·학원이 인용되면 곧 수강 신청으로 이어집니다." },
        { t: "h2", x: "'무엇을 배우는지'를 결과로 서술" },
        { t: "p", x: "커리큘럼 목차만 나열하지 말고, <b>수강 후 무엇을 할 수 있게 되는지</b>를 구체적 결과로 쓰세요. AI는 '학습 성과'에 답하려 합니다." },
        { t: "ul", items: [
          "대상 수준(입문/비전공/실무자)과 선수 지식을 명시",
          "학습 기간·시간·과제·수료 기준을 수치로",
          "수료 후 가능한 업무·프로젝트를 구체적으로",
        ] },
        { t: "h2", x: "학습자의 질문(CEP)에 답하기" },
        { t: "p", x: "\"비전공자도 따라갈 수 있나요?\", \"현업에 바로 쓸 수 있나요?\", \"수료증 주나요?\" 같은 실제 질문을 콘텐츠에 담으면 AI가 그대로 인용합니다." },
        { t: "quote", x: "학습자는 '강의 목차'가 아니라 '내 상황에서 이걸 배울 수 있는가'를 묻습니다." },
        { t: "h2", x: "성과·후기라는 근거" },
        { t: "p", x: "수료율, 만족도, 취업·이직 사례, 수강 후기 같은 <b>검증 가능한 성과</b>는 강력한 인용 재료입니다. 수치와 함께 텍스트로 제시하세요." },
        { t: "h2", x: "기술 기반" },
        { t: "ol", items: [
          "강의 소개 본문이 SSR로 읽히는지 확인",
          "Course/EducationalOrganization JSON-LD로 강의·기관 개체 정의",
          "자주 묻는 질문을 FAQPage로",
          "개강일·업데이트일로 최신성 유지",
        ] },
        { t: "p", x: "GeoScore로 강의 소개·커리큘럼 페이지를 진단하면, '배우기 좋은 강의' 질문에 얼마나 인용될 준비가 됐는지 점수와 처방으로 확인할 수 있습니다." },
      ],
    },
    en: {
      title: "Education GEO: Getting Courses & Academies Cited by AI",
      description:
        "GEO strategies for online courses, academies and educational content to get cited by AI for 'recommend a good course to learn ~' questions.",
      category: "Industry · Education",
      readMins: 6,
      blocks: [
        { t: "p", x: "\"Recommend a good data-analytics course for a non-major\" — learners ask AI about careers and learning paths. If the answer cites your course or academy, it turns into enrollments." },
        { t: "h2", x: "Describe 'what you'll learn' as outcomes" },
        { t: "p", x: "Don't just list a syllabus — write <b>what you'll be able to do after taking it</b> as concrete outcomes. AI tries to answer 'learning results'." },
        { t: "ul", items: [
          "State the target level (beginner/non-major/practitioner) and prerequisites",
          "Give duration, hours, assignments and completion criteria as numbers",
          "Describe the tasks/projects you can do after finishing",
        ] },
        { t: "h2", x: "Answer the learner's questions (CEP)" },
        { t: "p", x: "Put real questions — 'Can a non-major keep up?', 'Is it usable on the job right away?', 'Is there a certificate?' — into your content and AI can cite them directly." },
        { t: "quote", x: "Learners ask 'can I learn this in my situation?', not for a syllabus." },
        { t: "h2", x: "Outcomes and reviews as evidence" },
        { t: "p", x: "Completion rate, satisfaction, job/career outcomes and student reviews are <b>verifiable results</b> that make strong citation material. Present them in text with numbers." },
        { t: "h2", x: "Technical foundation" },
        { t: "ol", items: [
          "Confirm course descriptions render via SSR",
          "Define course/org entities with Course / EducationalOrganization JSON-LD",
          "Turn common questions into an FAQPage",
          "Keep freshness with start dates and update dates",
        ] },
        { t: "p", x: "Diagnose your course and curriculum pages with GeoScore to see, with a score and a prescription, how ready they are to be cited for 'best course to learn' questions." },
      ],
    },
  },
];

export function getArticle(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}
